# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: chris_milnes@hotmail.com
author_name: kvpmvp
contract_name: escrow_sale
deployment_language: python
preset_name: production
project_name: Hyperdrive

